version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mmo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mmo
      MYSQL_USER: phamlong
      MYSQL_PASSWORD: Long0403@
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/var/mysql:/var/lib/mysql